### ISSUE TITLE
$ne, $nin not working

### ISSUE THREAD

**Issue by zykyan** [Blagoj5/baze-packages#2]
{
    "success": false,
    "error": "Invalid _fieldName_: [object Object]"
}

**Comment by Blagoj5** [comment]
Hello, 

I Fixed this problem in version advanced-results@1.0.4 or @latest. So just update the package via
`npm install advanced-results@latest`.

NOTE: This happened to you because of this main reason:
I don't know what your URL parametars looked like, but in the docs i mentioned that if you don't see the special operator in THE TABLE in your case **$ne or $nin** you should just add it yourself, ex. ?field[$ne]=Tester, instead of doing ?field[ne]=Tester (**However if you have a mongodb sanitizer or some kind of sanitizer, it automatically deletes the operators because they see the DOLLAR SIGN $, as dangerous operator (which it is, you can cause injections and stuff)**. But thanks to your request i **added those 2 operators. So now you can freely do ?field[nin]=Sth,Sth1 or ?field[ne]=5**


Thanks for reporting this issue,
Tell me if the new update solves the problem so i can close this issue. By the way,  i just added new special paremeter/operator ?or for grouping fields inside MongoDB $or. Check it out if you want!
